#!/bin/bash

# New OS X versions come with Python Anaconda. This sort of screws up
# the environment and makes installing packages difficult
# use the anaconda pip to install itself and python.
# it will install it in the correct directory. Use this script
# to make aliases to the correct Python and Pip locations.
# try:

alias python="/usr/local/bin/python2.7"
alias pip="/usr/local/bin/pip"

# NOTE: aliases are not executed in bash scripts.
# you must execute these manually or put them in your bashrc file.
# I recommend using virtualenv though
