#!/bin/bash

# start session. format:
# <host>:<port>/session?game_id=<game id>&session_id=<session id>&player_id=<player id>

# game client 1 exposes a player session
curl "http://localhost:9090/session?game_id=sample_game&session_id=1&player_id=1"

# game client 2 follows
curl "http://localhost:9090/session?game_id=sample_game&session_id=1&player_id=2"
